### ISSUE TITLE
Rename CellectEx

### ISSUE THREAD

**Issue by marten** [zooniverse/cellect_ex#23]
It's horrible to pronounce and make the difference with Cellect clear. Suggested name: **"optate"**. It's a little more in the direction of "choosing with reason", which I guess fits well with this code going beyond simple random selection.

@zwolf @camallen  thoughts?

**Comment by camallen** [comment]
i don't even know the word optate. agree regarding cellect..will have a think, should we cast the net wider?

**Comment by marten** [comment]
Yeah, open to suggestions for anything that doesn't sound like "select".

**Comment by marten** [comment]
> **designate**
> _verb_ specify as selection

"Designator"?

**Comment by camallen** [comment]
I like that, for some reason an image of Arnie in Terminator 2 comes to mind.
